const messages = { M11: "Completa los campos obligatorios.", M27: "Las credenciales ingresadas no son válidas." };
const refs = { panel: document.getElementById("authPanel"), feedback: document.getElementById("authFeedback"), guideTitle: document.getElementById("authGuideTitle"), guideCopy: document.getElementById("authGuideCopy"), cursor: document.getElementById("authCursor"), toast: document.getElementById("toast") };
const modes = {
  passport: { label: "Passport", example: "Documento: 12345678 · Contraseña: ClaveSegura1", fields: `<div class="field-grid"><label class="field-label" for="documentType">Tipo de documento <span>*</span><select class="form-select" id="documentType"><option>DNI</option><option>CE</option></select></label><label class="field-label" for="documentNumber">Número de documento <span>*</span><input class="form-control" id="documentNumber" placeholder="Ingresa tu número" required></label></div><label class="field-label password-field" for="password">Contraseña <span>*</span><span class="password-input"><input class="form-control" id="password" type="password" required><button class="password-toggle" type="button" aria-label="Mostrar contraseña"><i class="fa-regular fa-eye"></i></button></span></label><div class="auth-secondary-actions"><a class="auth-recovery-link" href="index.html?auth=passport">Recuperar contraseña</a></div>` },
  document: { label: "Documento", example: "DNI: 74125896 · Nacimiento: 15/04/1988 · Emisión: 20/06/2020", fields: `<div class="document-grid"><label class="field-label" for="documentType">Tipo de documento <span>*</span><select class="form-select" id="documentType"><option>DNI</option><option>CE</option></select></label><label class="field-label" for="documentNumber">Número de documento <span>*</span><input class="form-control" id="documentNumber" placeholder="Ingresa tu número" required></label><label class="field-label" for="birthDate">Fecha de nacimiento <span>*</span><input class="form-control" id="birthDate" type="date" required></label><label class="field-label" for="issueDate">Fecha de emisión <span>*</span><input class="form-control" id="issueDate" type="date" required></label></div>` },
  autoregistro: { label: "Autoregistro", example: "Correo: ana.paredes@ejemplo.gob.pe · Contraseña: ClaveSegura1", fields: `<label class="field-label" for="email">Correo electrónico <span>*</span><input class="form-control" id="email" type="email" placeholder="usuario@ejemplo.gob.pe" required></label><label class="field-label password-field" for="password">Contraseña <span>*</span><span class="password-input"><input class="form-control" id="password" type="password" required><button class="password-toggle" type="button" aria-label="Mostrar contraseña"><i class="fa-regular fa-eye"></i></button></span></label><div class="auth-secondary-actions"><a class="auth-recovery-link" href="index.html?auth=autoregistro">Recuperar contraseña</a></div>` }
};
let mode = new URLSearchParams(window.location.search).get("auth") || "passport";
if (!modes[mode]) mode = "passport";
let guideStage = mode === "passport" ? "recovery" : mode === "document" ? "unsupported" : "select";
function showToast(message, type = "info") { const titles = { success: "Operación completada", error: "No se pudo completar", warning: "Revisa la información", info: "Información" }; const icons = { success: "fa-circle-check", error: "fa-circle-exclamation", warning: "fa-triangle-exclamation", info: "fa-circle-info" }; refs.toast.className = `toast toast-${type} is-visible`; refs.toast.setAttribute("role", "status"); refs.toast.setAttribute("aria-live", type === "error" || type === "warning" ? "assertive" : "polite"); refs.toast.setAttribute("aria-hidden", "false"); refs.toast.innerHTML = `<span class="toast-icon" aria-hidden="true"><i class="fa-solid ${icons[type] || icons.info}"></i></span><span class="toast-content"><strong class="toast-title">${titles[type] || titles.info}</strong><span class="toast-message"></span></span><button class="toast-close" type="button" aria-label="Cerrar aviso"><i class="fa-solid fa-xmark" aria-hidden="true"></i></button><span class="toast-progress" aria-hidden="true"></span>`; refs.toast.querySelector(".toast-message").textContent = message; window.clearTimeout(showToast.timer); const dismiss = () => { refs.toast.classList.remove("is-visible"); refs.toast.setAttribute("aria-hidden", "true"); }; refs.toast.querySelector(".toast-close").addEventListener("click", dismiss, { once: true }); showToast.timer = window.setTimeout(dismiss, 4500); }
function renderMode() {
  const config = modes[mode]; refs.feedback.hidden = true;
  refs.panel.innerHTML = `<form class="auth-panel-form" id="ref014LoginForm" novalidate>${config.fields}<div class="form-actions"><button class="btn btn-ssee button button-primary" type="submit"><i class="fa-solid fa-right-to-bracket"></i>Ingresar</button></div></form>`;
  document.querySelectorAll(".auth-tab").forEach((tab) => { const selected = tab.dataset.authMode === mode; tab.classList.toggle("is-active", selected); tab.setAttribute("aria-selected", selected); if (selected) { const box = tab.getBoundingClientRect(); refs.cursor.style.left = `${box.left + box.width / 2 - 8}px`; refs.cursor.style.top = `${box.top + box.height / 2 - 8}px`; } });
  document.querySelectorAll(".guide-mode-actions button").forEach((button) => button.classList.toggle("is-selected", button.dataset.guideMode === mode)); refs.guideTitle.textContent = guideStage === "recovery" ? `Recuperación ${config.label}` : guideStage === "unsupported" ? "Documento" : `Selecciona ${config.label}`; refs.guideCopy.textContent = guideStage === "recovery" ? `Presiona Recuperar contraseña para continuar con el flujo de ${config.label}.` : guideStage === "unsupported" ? "Este tipo de acceso no tiene recuperación de contraseña." : `Presiona la pestaña ${config.label} para continuar.`; refs.cursor.classList.add("is-visible");
  const target = guideStage === "recovery" ? refs.panel.querySelector(".auth-recovery-link") : document.querySelector(`.auth-tab[data-auth-mode="${mode}"]`); if (target) { const box = target.getBoundingClientRect(); refs.cursor.style.left = `${box.left + box.width / 2 - 8}px`; refs.cursor.style.top = `${box.top + box.height / 2 - 8}px`; }
  refs.panel.querySelector(".password-toggle")?.addEventListener("click", (event) => { const input = event.currentTarget.closest(".password-input").querySelector("input"); const visible = input.type === "text"; input.type = visible ? "password" : "text"; event.currentTarget.querySelector("i").className = `fa-regular ${visible ? "fa-eye" : "fa-eye-slash"}`; });
  refs.panel.querySelector("form").addEventListener("submit", validateMode); refs.panel.querySelector("input, select")?.focus();
}
function validateMode(event) { event.preventDefault(); const form = event.currentTarget; const values = [...form.querySelectorAll("input, select")].map((field) => field.value.trim()); if (values.some((value) => !value)) { refs.feedback.hidden = false; refs.feedback.textContent = messages.M11; showToast(messages.M11, "warning"); return; } const valid = mode === "passport" ? form.querySelector("#documentNumber").value === "12345678" && form.querySelector("#password").value === "ClaveSegura1" : mode === "document" ? form.querySelector("#documentNumber").value === "74125896" && form.querySelector("#birthDate").value === "1988-04-15" && form.querySelector("#issueDate").value === "2020-06-20" : form.querySelector("#email").value.toLowerCase() === "ana.paredes@ejemplo.gob.pe" && form.querySelector("#password").value === "ClaveSegura1"; if (!valid) { refs.feedback.hidden = false; refs.feedback.textContent = messages.M27; showToast(messages.M27, "warning"); return; } showToast("Autenticación validada correctamente.", "success"); }
document.querySelectorAll(".auth-tab").forEach((control) => control.addEventListener("click", () => { mode = control.dataset.authMode; guideStage = mode === "document" ? "unsupported" : "recovery"; const url = new URL(window.location.href); url.searchParams.set("auth", mode); window.history.replaceState({}, "", url); renderMode(); }));
document.querySelectorAll("[data-guide-mode]").forEach((control) => control.addEventListener("click", () => { mode = control.dataset.guideMode; guideStage = mode === "passport" ? "recovery" : "select"; const url = new URL(window.location.href); url.searchParams.set("auth", mode); window.history.replaceState({}, "", url); renderMode(); }));
renderMode();
