import { assignments } from "./data.js";
import { state } from "./state.js";
import { refs, enableTooltips, showToast } from "./ui.js";
import { closeMenus, openConfirmModal, closeConfirmModal } from "../../design-system/interaction.js";
import { getMessage } from "../../design-system/messages.js";
refs.emptyState.textContent = getMessage("M9");
function statusClass(status) { return status === "Finalizada" ? "active" : status === "Anulada" ? "expired" : status === "En proceso" || status === "Reasignada" ? "warning" : ""; }
export function renderAssignments() { refs.assignmentsBody.innerHTML = state.filteredAssignments.map((assignment) => { const index = assignments.indexOf(assignment); const canReassign = !["Finalizada", "Anulada"].includes(assignment.status); return `<tr><td><strong>${assignment.instrument}</strong></td><td>${assignment.user}</td><td>${assignment.sample}</td><td>${assignment.start}</td><td>${assignment.end}</td><td>${assignment.progress}</td><td><span class="status ${statusClass(assignment.status)}">${assignment.status}</span></td><td><div class="row-actions"><button class="row-action" type="button" data-action="view" data-index="${index}" title="Ver detalle"><i class="fa-regular fa-eye" aria-hidden="true"></i><span>Ver detalle</span></button>${canReassign ? `<button class="row-action" type="button" data-action="reassign" data-index="${index}" title="Reasignar"><i class="fa-solid fa-arrows-rotate" aria-hidden="true"></i><span>Reasignar</span></button><button class="row-action" type="button" data-action="remove" data-index="${index}" title="Anular"><i class="fa-solid fa-ban" aria-hidden="true"></i><span>Anular</span></button>` : ""}</div></td></tr>`; }).join(""); refs.emptyState.hidden = state.filteredAssignments.length > 0; refs.pageSummary.textContent = state.filteredAssignments.length ? `Mostrando 1 a ${state.filteredAssignments.length} de ${state.filteredAssignments.length} registros` : "Mostrando 0 registros"; refs.assignmentCount.textContent = `${assignments.length} asignaciones registradas`; enableTooltips(); }
export function applyFilters() { const query = document.getElementById("filterQuery").value.trim().toLowerCase(); const instrument = document.getElementById("filterInstrument").value.trim().toLowerCase(); const user = document.getElementById("filterUser").value.trim().toLowerCase(); const sample = document.getElementById("filterSample").value.trim().toLowerCase(); const start = document.getElementById("filterStart").value; const end = document.getElementById("filterEnd").value; const status = document.getElementById("filterStatus").value; const period = document.getElementById("filterPeriod").value; const progress = document.getElementById("filterProgress").value; state.filteredAssignments = assignments.filter((assignment) => { const searchable = [assignment.id, assignment.instrument, assignment.user, assignment.sample, assignment.start, assignment.end, assignment.progress, assignment.status].join(" ").toLowerCase(); const startIso = assignment.start.split("/").reverse().join("-"); const endIso = assignment.end.split("/").reverse().join("-"); return searchable.includes(query) && assignment.instrument.toLowerCase().includes(instrument) && assignment.user.toLowerCase().includes(user) && assignment.sample.toLowerCase().includes(sample) && (!start || startIso === start) && (!end || endIso === end) && (status === "Todos" || assignment.status === status) && (period === "Todos" || assignment.period === period) && (progress === "Todos" || assignment.progressGroup === progress); }); renderAssignments(); }
 function openAssignment(index = null) { state.editingIndex = index; const assignment = index === null ? null : assignments[index]; refs.assignmentTitle.textContent = assignment ? "Reasignar instrumento" : "Registrar asignación"; refs.assignmentSaveBtn.textContent = "Guardar"; refs.assignmentContext.textContent = assignment ? `Actualiza la asignación de ${assignment.instrument} para ${assignment.user}.` : "Selecciona los elementos que participarán en la asignación."; refs.assignmentInstrument.value = assignment?.instrument || "Ficha de seguimiento"; refs.assignmentUser.value = assignment?.user || "Ana Paredes"; refs.assignmentSample.value = assignment?.sample || "Muestra nacional 2026"; refs.assignmentStart.value = assignment ? assignment.start.split("/").reverse().join("-") : "2026-08-18"; refs.assignmentEnd.value = assignment ? assignment.end.split("/").reverse().join("-") : "2026-09-18"; bootstrap.Modal.getOrCreateInstance(refs.assignmentModal).show(); }
export function handleAction(event) { const action = event.target.closest("[data-action]"); if (!action) return; const index = Number(action.dataset.index); const assignment = assignments[index]; if (action.dataset.action === "view") showToast(refs.toast, `${assignment.instrument} está ${assignment.status} con un progreso de ${assignment.progress}.`, "info"); if (action.dataset.action === "reassign") openAssignment(index); if (action.dataset.action === "remove") { state.pendingAssignment = { index, remove: true }; openConfirmModal("confirmModal", `Vas a anular la asignación de ${assignment.instrument} para ${assignment.user}. ¿Deseas continuar?`); } }
export function openNewAssignment() { openAssignment(); }
export function saveAssignment(event) { event.preventDefault(); const payload = { instrument: refs.assignmentInstrument.value, user: refs.assignmentUser.value, sample: refs.assignmentSample.value, start: refs.assignmentStart.value.split("-").reverse().join("/"), end: refs.assignmentEnd.value.split("-").reverse().join("/"), period: refs.assignmentStart.value.slice(0, 4), progress: "0%", progressGroup: "Sin iniciar", status: "Pendiente", updated: "18/08/2026 09:30" }; if (state.editingIndex === null) { payload.id = `ASN-${String(assignments.length + 1).padStart(3, "0")}`; assignments.unshift(payload); bootstrap.Modal.getOrCreateInstance(refs.assignmentModal).hide(); renderAssignments(); showToast(refs.toast, "Asignación registrada correctamente.", "success"); return; } state.pendingAssignment = { index: state.editingIndex, payload }; openConfirmModal("confirmModal", `La reasignación cambiará el instrumento asignado a ${payload.user}. ¿Deseas continuar?`); }
export function confirmAction() { if (!state.pendingAssignment) return; const pending = state.pendingAssignment; if (pending.remove) { assignments[pending.index].status = "Anulada"; assignments[pending.index].updated = "18/08/2026 09:30"; showToast(refs.toast, "Asignación anulada correctamente.", "success"); } else { assignments[pending.index] = { ...assignments[pending.index], ...pending.payload, status: "Reasignada", updated: "18/08/2026 09:30" }; bootstrap.Modal.getOrCreateInstance(refs.assignmentModal).hide(); showToast(refs.toast, "Asignación reasignada correctamente.", "success"); } state.pendingAssignment = null; closeConfirmModal("confirmModal"); renderAssignments(); }
