import { assignmentState, cancelAssignment, findUser, isEditableAssignment, loadAssignments } from "./data.js";
import { downloadExcel, escapeHtml, getParam, linkTo, openConfirm, qs, showToast, closeConfirm } from "./common.js";
import { createDateRangeFilter } from "../../design-system/date-range.js";
import { attachTableSorting } from "../../design-system/table-sort.js";

let assignments = loadAssignments(); let filtered = [...assignments]; let page = 1; let pendingCancel = null;
const periodRange = createDateRangeFilter(qs("[data-date-range]"));
function toIso(value) { const [day, month, year] = value.split("/"); return `${year}-${month}-${day}`; }
function displayStatus(assignment) { return assignmentState(assignment); }
function statusClass(status) { return status === "Activa" ? "active" : "inactive"; }
function uniqueValues(key) { return [...new Set(assignments.map((item) => item[key]).filter(Boolean))]; }
function populateOptions() { qs("#filterProject").insertAdjacentHTML("beforeend", uniqueValues("project").map((item) => `<option>${escapeHtml(item)}</option>`).join("")); qs("#filterInstrument").insertAdjacentHTML("beforeend", uniqueValues("instrument").map((item) => `<option>${escapeHtml(item)}</option>`).join("")); qs("#filterSample").insertAdjacentHTML("beforeend", uniqueValues("sample").map((item) => `<option>${escapeHtml(item)}</option>`).join("")); qs("#filterDre").insertAdjacentHTML("beforeend", uniqueValues("dre").map((item) => `<option>${escapeHtml(item)}</option>`).join("")); qs("#filterUgel").insertAdjacentHTML("beforeend", uniqueValues("ugel").map((item) => `<option>${escapeHtml(item)}</option>`).join("")); }
function getFilters() { return { query: qs("#filterQuery").value.trim().toLowerCase(), project: qs("#filterProject").value, instrument: qs("#filterInstrument").value, sample: qs("#filterSample").value, dre: qs("#filterDre").value, ugel: qs("#filterUgel").value, registrar: qs("#filterRegistrar").value.trim().toLowerCase(), informant: qs("#filterInformant").value.trim().toLowerCase(), start: qs("#filterStart").value, end: qs("#filterEnd").value, status: qs("#filterStatus").value }; }
function applyFilters() {
  const filters = getFilters(); filtered = assignments.filter((assignment) => { const user = findUser(assignment.userId); const status = displayStatus(assignment); const searchable = [assignment.id, assignment.unitId, assignment.project, assignment.instrument, assignment.sample, assignment.userId, user.name, assignment.dre, assignment.ugel, assignment.registrarId, assignment.informantId, assignment.start, assignment.end, status].join(" ").toLowerCase(); return (!filters.query || searchable.includes(filters.query)) && (!filters.project || assignment.project === filters.project) && (!filters.instrument || assignment.instrument === filters.instrument) && (!filters.sample || assignment.sample === filters.sample) && (!filters.dre || assignment.dre === filters.dre) && (!filters.ugel || assignment.ugel === filters.ugel) && (!filters.registrar || assignment.registrarId.toLowerCase().includes(filters.registrar)) && (!filters.informant || assignment.informantId.toLowerCase().includes(filters.informant)) && (!filters.start || toIso(assignment.start) >= filters.start) && (!filters.end || toIso(assignment.end) <= filters.end) && (!filters.status || status === filters.status); }); page = 1; render(); return filtered.length;
}
function renderSummary() { qs("#assignmentCount").textContent = `${assignments.length} asignaciones registradas`; qs("#summaryTotal").textContent = assignments.length; qs("#summaryPending").textContent = assignments.filter((item) => item.active !== false && item.status === "Pendiente").length; qs("#summaryProgress").textContent = assignments.filter((item) => item.active !== false && item.status === "En proceso").length; qs("#summaryComplete").textContent = assignments.filter((item) => item.active !== false && item.status === "Finalizada").length; }
function renderRows() {
  const pageSize = Number(qs("#pageSize").value); const offset = (page - 1) * pageSize; const visible = filtered.slice(offset, offset + pageSize);
  qs("#assignmentsBody").innerHTML = visible.map((assignment) => { const user = findUser(assignment.userId); const canEdit = isEditableAssignment(assignment); const canManage = assignment.active !== false && !["Finalizada", "Anulada"].includes(assignment.status); const actions = `<a class="row-action" href="${linkTo("detail.html", { id: assignment.id })}" title="Ver detalle"><i class="fa-regular fa-eye" aria-hidden="true"></i><span>Ver detalle</span></a>${canEdit ? `<a class="row-action" href="${linkTo("edit.html", { id: assignment.id })}" title="Editar"><i class="fa-solid fa-pen" aria-hidden="true"></i><span>Editar</span></a>` : ""}${canManage ? `<a class="row-action" href="${linkTo("reassign.html", { id: assignment.id })}" title="Reasignar"><i class="fa-solid fa-arrows-rotate" aria-hidden="true"></i><span>Reasignar</span></a><button class="row-action" type="button" data-action="cancel" data-id="${escapeHtml(assignment.id)}" title="Anular"><i class="fa-solid fa-ban" aria-hidden="true"></i><span>Anular</span></button>` : ""}`; const status = displayStatus(assignment); const operationalStatus = assignment.status; return `<tr><td>${offset + visible.indexOf(assignment) + 1}</td><td>${escapeHtml(assignment.unitId || `UN-${assignment.id.slice(-3)}`)}</td><td>${escapeHtml(assignment.project)}</td><td>${escapeHtml(assignment.instrument)}</td><td>${escapeHtml(assignment.sample)}</td><td>${escapeHtml(assignment.dre)}</td><td>${escapeHtml(assignment.ugel)}</td><td>${escapeHtml(assignment.registrarId)}</td><td>${escapeHtml(assignment.informantId)}</td><td>${escapeHtml(assignment.start)}</td><td><span class="status operational-status">${escapeHtml(operationalStatus)}</span></td><td><span class="status ${statusClass(status)}">${escapeHtml(status)}</span></td><td><div class="row-actions">${actions}</div></td></tr>`; }).join("");
  qs("#emptyState").hidden = filtered.length > 0; qs("#pageSummary").textContent = filtered.length ? `Mostrando ${offset + 1} a ${Math.min(offset + pageSize, filtered.length)} de ${filtered.length} registros` : "Mostrando 0 registros";
}
function renderPagination() { const pageSize = Number(qs("#pageSize").value); const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); page = Math.min(page, totalPages); const button = (label, target, disabled, current = false) => `<button class="page-btn${current ? " is-current" : ""}" type="button" data-page="${target}"${disabled ? " disabled" : ""}>${label}</button>`; qs("#pagination").innerHTML = button("«", 1, page === 1) + button("‹", page - 1, page === 1) + Array.from({ length: totalPages }, (_, index) => button(index + 1, index + 1, false, index + 1 === page)).join("") + button("›", page + 1, page === totalPages) + button("»", totalPages, page === totalPages); }
function render() { renderSummary(); renderRows(); renderPagination(); }

qs("#filterForm").addEventListener("submit", (event) => { event.preventDefault(); if (periodRange && !periodRange.validate()) return showToast("Revisa el rango de fechas seleccionado.", "warning"); const count = applyFilters(); showToast(count ? "Filtros aplicados." : "No se encontraron asignaciones con los criterios seleccionados.", count ? "info" : "warning"); });
qs("#filterQuery").addEventListener("input", applyFilters); qs("#filterToggle").addEventListener("click", () => { const open = qs("#filterForm").classList.toggle("is-expanded"); qs("#filterToggle").setAttribute("aria-expanded", String(open)); });
qs("#clearBtn").addEventListener("click", () => { qs("#filterForm").reset(); periodRange?.reset(); applyFilters(); showToast("Filtros limpiados.", "info"); }); qs("#pageSize").addEventListener("change", () => { page = 1; render(); });
qs("#pagination").addEventListener("click", (event) => { const button = event.target.closest("[data-page]"); if (button && !button.disabled) { page = Number(button.dataset.page); render(); } });
qs("#assignmentsBody").addEventListener("click", (event) => { const button = event.target.closest("[data-action=cancel]"); if (!button) return; pendingCancel = button.dataset.id; openConfirm("La asignación seleccionada quedará anulada y no podrá ser reasignada."); });
qs("#confirmAction").addEventListener("click", () => { if (!pendingCancel) return; assignments = cancelAssignment(pendingCancel); filtered = [...assignments]; pendingCancel = null; closeConfirm(); applyFilters(); showToast("Asignación anulada correctamente.", "success"); });
qs("#exportBtn").addEventListener("click", () => { if (!filtered.length) return showToast("No existen registros para exportar.", "warning"); downloadExcel("asignaciones.xls", ["N.°", "ID unidad", "Proyecto", "Instrumento", "Muestra", "DRE", "UGEL", "Usuario registrador", "Usuario informante", "Fecha de asignación", "Estado operativo", "Estado"], filtered.map((item, index) => [index + 1, item.unitId || `UN-${item.id.slice(-3)}`, item.project, item.instrument, item.sample, item.dre, item.ugel, item.registrarId, item.informantId, item.start, item.status, displayStatus(item)])); showToast("Archivo Excel generado correctamente.", "success"); });

populateOptions(); render(); attachTableSorting(qs(".assignment-table table")); const result = getParam("result"); if (result === "created") showToast("Asignación registrada correctamente.", "success"); if (result === "reassigned") showToast("Asignación reasignada correctamente.", "success"); if (result === "updated") showToast("Asignación actualizada correctamente.", "success");
