const messages = { M11: "Completa los campos obligatorios.", M23: "El periodo de autoregistro no se encuentra habilitado.", M24: "El periodo habilitado para el autoregistro ha finalizado.", M27: "Las credenciales ingresadas no son válidas." };
const getMessage = (key) => messages[key] || key;
const getPrototypeMessage = (key) => key === "authenticationSuccess" ? "Autenticación validada correctamente." : key;
function renderToast(element, message, type = "info") { const titles = { success: "Operación completada", error: "No se pudo completar", warning: "Revisa la información", info: "Información" }; const icons = { success: "fa-circle-check", error: "fa-circle-exclamation", warning: "fa-triangle-exclamation", info: "fa-circle-info" }; element.className = `toast toast-${type} is-visible`; element.setAttribute("role", "status"); element.setAttribute("aria-live", type === "error" || type === "warning" ? "assertive" : "polite"); element.setAttribute("aria-hidden", "false"); element.innerHTML = `<span class="toast-icon" aria-hidden="true"><i class="fa-solid ${icons[type] || icons.info}"></i></span><span class="toast-content"><strong class="toast-title">${titles[type] || titles.info}</strong><span class="toast-message"></span></span><button class="toast-close" type="button" aria-label="Cerrar aviso"><i class="fa-solid fa-xmark" aria-hidden="true"></i></button><span class="toast-progress" aria-hidden="true"></span>`; element.querySelector(".toast-message").textContent = message; window.clearTimeout(renderToast.timeoutId); const dismiss = () => { element.classList.remove("is-visible"); element.setAttribute("aria-hidden", "true"); }; element.querySelector(".toast-close").addEventListener("click", dismiss, { once: true }); renderToast.timeoutId = window.setTimeout(dismiss, 4500); }
function recordAuthAttempt(args) { try { const key = "ssee-auth-audit"; const current = JSON.parse(sessionStorage.getItem(key) || "[]"); sessionStorage.setItem(key, JSON.stringify([{ ...args, timestamp: new Date().toISOString(), operation: "Inicio de sesión" }, ...current].slice(0, 50))); } catch { /* La demo sigue disponible si el almacenamiento está bloqueado. */ } }
function hasRequiredValues(values) { return values.every((value) => String(value ?? "").trim().length > 0); }
function validatePassportAccess({ documentNumber, password, user }) { return Boolean(user) && user.password === password && user.documentNumber === documentNumber && user.active && user.synchronized && user.projects > 0 && user.roles > 0; }
function validateDocumentAccess({ documentNumber, birthDate, issueDate, user }) { return Boolean(user) && user.number === documentNumber && user.birthDate === birthDate && user.issueDate === issueDate && user.active && user.valid && user.projects > 0 && user.roles > 0; }
function validateAutoregisterAccess({ email, password, account, periodState }) { return periodState === "open" && Boolean(account) && account.email === email && account.password === password && account.active; }

const refs = { panel: document.getElementById("authPanel"), feedback: document.getElementById("authFeedback"), success: document.getElementById("authSuccess"), successCopy: document.getElementById("authSuccessCopy"), continueButton: document.getElementById("continueBtn"), authWelcome: document.getElementById("authWelcome"), authPage: document.querySelector(".auth-page"), toast: document.getElementById("toast"), guide: document.getElementById("authGuide"), guideTitle: document.getElementById("authGuideTitle"), guideCopy: document.getElementById("authGuideCopy"), cursor: document.getElementById("authCursor") };

const modes = {
  passport: { label: "Passport", example: "Documento: 12345678 · Contraseña: ClaveSegura1", success: "Las credenciales Passport fueron validadas y tu cuenta cumple las condiciones de acceso.", fields: `<div class="field-grid"><label class="field-label" for="documentType">Tipo de documento <span>*</span><select class="form-select" id="documentType"><option>DNI</option><option>CE</option></select></label><label class="field-label" for="documentNumber">Número de documento <span>*</span><input class="form-control" id="documentNumber" autocomplete="username" placeholder="Ingresa tu número" required></label></div><label class="field-label password-field" for="password">Contraseña <span>*</span><span class="password-input"><input class="form-control" id="password" type="password" autocomplete="current-password" required><button class="password-toggle" type="button" aria-label="Mostrar contraseña"><i class="fa-regular fa-eye"></i></button></span></label><div class="auth-secondary-actions"><a class="auth-recovery-link" href="../ref-013-password-recovery/index.html?auth=passport">Recuperar contraseña</a></div>` },
  document: { label: "Documento", example: "DNI: 74125896 · Nacimiento: 15/04/1988 · Emisión: 20/06/2020", success: "Los datos del documento fueron validados y tu cuenta cumple las condiciones de acceso.", fields: `<div class="document-grid"><label class="field-label" for="documentType">Tipo de documento <span>*</span><select class="form-select" id="documentType"><option>DNI</option><option>CE</option></select></label><label class="field-label" for="documentNumber">Número de documento <span>*</span><input class="form-control" id="documentNumber" autocomplete="username" placeholder="Ingresa tu número" required></label><label class="field-label" for="birthDate">Fecha de nacimiento <span>*</span><input class="form-control" id="birthDate" type="date" required></label><label class="field-label" for="issueDate">Fecha de emisión <span>*</span><input class="form-control" id="issueDate" type="date" required></label></div>` },
  autoregistro: { label: "Autoregistro", example: "Correo: ana.paredes@ejemplo.gob.pe · Contraseña: ClaveSegura1", success: "La cuenta y el proceso asociado están habilitados para ingresar a S.S.E.E.", fields: `<label class="field-label" for="email">Correo electrónico <span>*</span><input class="form-control" id="email" type="email" autocomplete="username" placeholder="usuario@ejemplo.gob.pe" required></label><label class="field-label password-field" for="password">Contraseña <span>*</span><span class="password-input"><input class="form-control" id="password" type="password" autocomplete="current-password" required><button class="password-toggle" type="button" aria-label="Mostrar contraseña"><i class="fa-regular fa-eye"></i></button></span></label><div class="auth-secondary-actions"><a class="auth-recovery-link" href="../ref-013-password-recovery/index.html?auth=autoregistro">Recuperar contraseña</a></div>` }
};

let mode = new URLSearchParams(window.location.search).get("auth") || "passport";
if (!modes[mode]) mode = "passport";
const periodState = new URLSearchParams(window.location.search).get("period") || "open";

function showToast(message, type = "info") { renderToast(refs.toast, message, type); }
function showError(message) { refs.feedback.hidden = false; refs.feedback.textContent = message; }
function clearState() { refs.feedback.hidden = true; refs.success.hidden = true; }
function bindPasswordToggle() { refs.panel.querySelector(".password-toggle")?.addEventListener("click", (event) => { const button = event.currentTarget; const input = button.closest(".password-input").querySelector("input"); const visible = input.type === "text"; input.type = visible ? "password" : "text"; button.querySelector("i").className = `fa-regular ${visible ? "fa-eye" : "fa-eye-slash"}`; button.setAttribute("aria-label", visible ? "Mostrar contraseña" : "Ocultar contraseña"); }); }
function renderMode() { const config = modes[mode]; clearState(); refs.panel.innerHTML = `<form class="auth-panel-form" id="centralLoginForm" novalidate>${config.fields}<div class="form-actions"><button class="btn btn-ssee button button-primary" type="submit"><i class="fa-solid fa-right-to-bracket" aria-hidden="true"></i>Ingresar</button></div></form>`; document.querySelectorAll(".auth-tab").forEach((tab) => { const active = tab.dataset.authMode === mode; tab.classList.toggle("is-active", active); tab.setAttribute("aria-selected", active ? "true" : "false"); if (active) { const box = tab.getBoundingClientRect(); refs.cursor.style.left = `${box.left + box.width / 2 - 8}px`; refs.cursor.style.top = `${box.top + box.height / 2 - 8}px`; } }); bindPasswordToggle(); refs.guide.hidden = false; refs.cursor.classList.add("is-visible"); refs.guideTitle.textContent = `Acceso ${config.label}`; refs.guideCopy.textContent = `Completa los campos de ${config.label} y presiona Ingresar. Ejemplo válido: ${config.example}.`; refs.panel.querySelector("input, select")?.focus(); refs.panel.querySelector("form").addEventListener("submit", validateMode); }
function validateMode(event) { event.preventDefault(); clearState(); const form = event.currentTarget; const values = [...form.querySelectorAll("input, select")]; const user = mode === "autoregistro" ? form.querySelector("#email")?.value.trim() : form.querySelector("#documentNumber")?.value.trim(); if (mode === "autoregistro" && periodState !== "open") { const messageKey = periodState === "closed" ? "M23" : "M24"; recordAuthAttempt({ user: user || "No identificado", authType: "Autoregistro", result: "Fallida", reason: periodState === "closed" ? "Proceso no habilitado" : "Vigencia vencida" }); showError(getMessage(messageKey)); showToast(getMessage(messageKey), "warning"); return; } if (!hasRequiredValues(values.map((field) => field.value))) { recordAuthAttempt({ user: user || "No identificado", authType: modes[mode].label, result: "Fallida", reason: "Datos incompletos" }); showError(getMessage("M11")); showToast(getMessage("M11"), "warning"); return; } let valid = false; if (mode === "passport") valid = validatePassportAccess({ documentNumber: form.querySelector("#documentNumber").value.trim(), password: form.querySelector("#password").value, user: { documentNumber: "12345678", password: "ClaveSegura1", active: true, synchronized: true, projects: 1, roles: 1 } }); if (mode === "document") valid = validateDocumentAccess({ documentNumber: form.querySelector("#documentNumber").value.trim(), birthDate: form.querySelector("#birthDate").value, issueDate: form.querySelector("#issueDate").value, user: { number: "74125896", birthDate: "1988-04-15", issueDate: "2020-06-20", active: true, valid: true, projects: 1, roles: 1 } }); if (mode === "autoregistro") valid = validateAutoregisterAccess({ email: form.querySelector("#email").value.trim().toLowerCase(), password: form.querySelector("#password").value, account: { email: "ana.paredes@ejemplo.gob.pe", password: "ClaveSegura1", active: true }, periodState }); if (!valid) { recordAuthAttempt({ user: user || "No identificado", authType: modes[mode].label, result: "Fallida", reason: "Credenciales inválidas o acceso no autorizado" }); showError(getMessage("M27")); showToast(getMessage("M27"), "warning"); return; } recordAuthAttempt({ user, authType: modes[mode].label, result: "Exitosa" }); form.hidden = true; refs.successCopy.textContent = modes[mode].success; refs.success.hidden = false; showToast(getPrototypeMessage("authenticationSuccess"), "success"); }
document.querySelectorAll(".auth-tab").forEach((tab) => tab.addEventListener("click", () => { mode = tab.dataset.authMode; const url = new URL(window.location.href); url.searchParams.set("auth", mode); window.history.replaceState({}, "", url); renderMode(); }));
refs.continueButton.addEventListener("click", () => { refs.authPage.hidden = true; refs.authWelcome.hidden = false; mountAuthWelcome(refs.authWelcome, mode === "autoregistro" ? "autoregistro" : mode); });
renderMode();
