import { samples } from "./data.js";
import { state } from "./state.js";
import { refs, enableTooltips, showToast, showForm, showList } from "./ui.js";
import { closeMenus, openConfirmModal, closeConfirmModal } from "../../design-system/interaction.js";
function statusClass(status) { return status === "Publicada" ? "active" : status === "Anulada" ? "expired" : status === "Configurada" ? "warning" : status === "Cerrada" ? "inactive" : ""; }
export function renderSamples() { refs.samplesBody.innerHTML = state.filteredSamples.map((sample) => { const index = samples.indexOf(sample); return `<tr><td><strong>${sample.id}</strong></td><td><strong>${sample.name}</strong><div class="description">${sample.description}</div></td><td>${sample.intervention}</td><td>${sample.period}</td><td>${sample.source}</td><td>${sample.units}</td><td><span class="status ${statusClass(sample.status)}">${sample.status}</span></td><td><div class="action-menu"><button class="menu-btn" type="button" data-menu-button="${index}" aria-expanded="false" aria-label="Abrir acciones de ${sample.name}"><i class="fa-solid fa-ellipsis-vertical"></i></button><div class="legacy-dropdown" data-menu-panel="${index}" hidden><button type="button" data-action="view" data-index="${index}"><i class="fa-regular fa-eye"></i>Ver detalle</button><button type="button" data-action="edit" data-index="${index}"><i class="fa-regular fa-pen-to-square"></i>Editar</button><button type="button" data-action="clone" data-index="${index}"><i class="fa-regular fa-copy"></i>Clonar</button></div></div></td></tr>`; }).join(""); refs.emptyState.hidden = state.filteredSamples.length > 0; refs.pageSummary.textContent = state.filteredSamples.length ? `Mostrando 1 a ${state.filteredSamples.length} de ${state.filteredSamples.length} registros` : "Mostrando 0 registros"; refs.sampleCount.textContent = `${samples.length} muestras registradas`; enableTooltips(); }
export function applyFilters() { const query = refs.filterQuery.value.trim().toLowerCase(); const status = refs.filterStatus.value; const period = refs.filterPeriod.value; const intervention = refs.filterIntervention.value; state.filteredSamples = samples.filter((sample) => [sample.id, sample.name, sample.intervention, sample.source, sample.status].join(" ").toLowerCase().includes(query) && (status === "Todos" || sample.status === status) && (period === "Todos" || sample.period === period) && (intervention === "Todos" || sample.intervention === intervention)); renderSamples(); }
export function handleAction(event) { const menu = event.target.closest("[data-menu-button]"); const action = event.target.closest("[data-action]"); if (menu) { const panel = refs.samplesBody.querySelector(`[data-menu-panel='${menu.dataset.menuButton}']`); const opening = panel?.hidden; closeMenus(refs.samplesBody); if (opening && panel) { panel.hidden = false; menu.setAttribute("aria-expanded", "true"); } return; } if (!action) return; closeMenus(refs.samplesBody); const sample = samples[Number(action.dataset.index)]; if (action.dataset.action === "edit") { state.editingIndex = samples.indexOf(sample); showForm(sample); } else if (action.dataset.action === "clone") { samples.unshift({ ...sample, id: `MST-${String(samples.length + 1).padStart(3, "0")}`, name: `${sample.name} - copia`, status: "Borrador", updated: "18/08/2026 09:30" }); applyFilters(); showToast(refs.toast, "Muestra clonada como borrador.", "success"); } else { showToast(refs.toast, `${sample.name}: ${sample.units} unidades en estado ${sample.status}.`, "info"); } }
export function saveSample(event) { event.preventDefault(); refs.nameError.textContent = refs.sampleName.value.trim() ? "" : "Ingresa el nombre de la muestra."; refs.descriptionError.textContent = refs.sampleDescription.value.trim() ? "" : "Ingresa la descripción de la muestra."; if (!refs.sampleName.value.trim() || !refs.sampleDescription.value.trim() || !refs.sampleSource.value || !refs.sampleIntervention.value || !refs.samplePeriod.value) { showToast(refs.toast, "Completa los campos obligatorios.", "warning"); return; } const previous = state.editingIndex === null ? null : samples[state.editingIndex]; const payload = { id: previous?.id || `MST-${String(samples.length + 1).padStart(3, "0")}`, name: refs.sampleName.value.trim(), description: refs.sampleDescription.value.trim(), source: refs.sampleSource.value, intervention: refs.sampleIntervention.value, period: refs.samplePeriod.value, units: previous?.units || "0", status: previous?.status || "Borrador", updated: "18/08/2026 09:30" }; if (previous) samples[state.editingIndex] = payload; else samples.unshift(payload); state.editingIndex = null; applyFilters(); showList(); showToast(refs.toast, "Muestra registrada correctamente.", "success"); }
