import { samples, sampleUnitCatalog } from "./data.js";
import { state, getSourceConfig, resetWizard } from "./state.js";
import { refs, enableTooltips, showToast, showForm, showList, setFormStep, clearErrors, updateDraft, renderAvailableFields, renderFields, renderUnits } from "./ui.js";
import { openConfirmModal, closeConfirmModal, getConfirmReason, validateConfirmReason } from "../../design-system/interaction.js";
import { getMessage } from "../../design-system/messages.js";

const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]));
function statusClass(status) { return status === "Activa" ? "active" : status === "Inactiva" ? "inactive" : ""; }

export function renderSamples() { const header = refs.samplesBody.closest("table")?.querySelector("thead tr"); if (header && !header.querySelector("[data-column='row-number']")) header.insertAdjacentHTML("afterbegin", '<th data-column="row-number">N.°</th>'); refs.samplesBody.innerHTML = state.filteredSamples.map((sample) => { const index = samples.indexOf(sample); return `<tr><td>${index + 1}</td><td><strong>${escapeHtml(sample.id)}</strong></td><td><strong>${escapeHtml(sample.name)}</strong><div class="description">${escapeHtml(sample.description)}</div></td><td>${escapeHtml(sample.source)}</td><td>${escapeHtml(sample.units)}</td><td><span class="status ${statusClass(sample.status)}">${escapeHtml(sample.status)}</span></td><td><div class="row-actions"><button class="row-action" type="button" data-action="view" data-index="${index}" title="Ver detalle"><i class="fa-regular fa-eye" aria-hidden="true"></i><span>Ver detalle</span></button><button class="row-action" type="button" data-action="edit" data-index="${index}" title="Editar"><i class="fa-solid fa-pen" aria-hidden="true"></i><span>Editar</span></button></div></td></tr>`; }).join(""); refs.emptyState.hidden = state.filteredSamples.length > 0; refs.pageSummary.textContent = state.filteredSamples.length ? `Mostrando 1 a ${state.filteredSamples.length} de ${state.filteredSamples.length} registros` : "Mostrando 0 registros"; refs.sampleCount.textContent = `${samples.length} muestras registradas`; enableTooltips(); }
export function applyFilters() { const query = refs.filterQuery.value.trim().toLowerCase(); const source = refs.filterSource.value, status = refs.filterStatus.value; state.filteredSamples = samples.filter((sample) => { const searchable = [sample.id, sample.name, sample.description, sample.source, sample.units, sample.status].join(" ").toLowerCase(); return searchable.includes(query) && (source === "Todos" || sample.source === source) && (status === "Todos" || sample.status === status); }); renderSamples(); }

export function prepareUnits() { if (!state.draft) return; const population = Number(state.draft.population || 0); const total = state.draft.selectionMethod === "Total" ? population : Number(state.draft.sampleSize || 0); const amount = Math.min(total, 10); const current = state.draft.units || []; const targetAmount = current.length ? current.length : amount; state.draft.unitTotal = total; state.draft.units = Array.from({ length: targetAmount }, (_, index) => ({ ...sampleUnitCatalog[index % sampleUnitCatalog.length], ...(current[index] || {}), id: current[index]?.id || sampleUnitCatalog[index % sampleUnitCatalog.length].id })); }

export function handleAction(event) { const action = event.target.closest("[data-action]"); if (!action) return; if (["move-field-up", "move-field-down", "remove-field"].includes(action.dataset.action)) { const index = Number(action.dataset.fieldIndex); if (action.dataset.action === "remove-field") state.draft.fields.splice(index, 1); else { const next = action.dataset.action === "move-field-up" ? index - 1 : index + 1; if (state.draft.fields[next]) [state.draft.fields[index], state.draft.fields[next]] = [state.draft.fields[next], state.draft.fields[index]]; } state.dirty = true; renderAvailableFields(); renderFields(); return; } if (action.dataset.unitAction === "replace") { openReplacementModal(action.dataset.unitId); return; } if (action.dataset.unitAction === "exclude") { state.pendingUnitAction = { type: "exclude", unitId: action.dataset.unitId }; openConfirmModal("confirmModal", "¿Está seguro que desea excluir esta unidad de la muestra?"); return; } const sample = samples[Number(action.dataset.index)]; if (!sample) return; if (action.dataset.action === "view") { showDetail(sample); return; } if (action.dataset.action === "edit") { state.editingIndex = samples.indexOf(sample); state.draft = { ...sample, fields: sample.fields?.map((field, index) => ({ informant: false, user: index === 0, ...field })), units: sample.unitList?.map((unit) => ({ ...unit })), instruments: [...(sample.instruments || [])] }; showForm(sample); return; } }

function showDetail(sample) { const fields = sample.fields || [], units = sample.unitList || [], instruments = sample.instruments || []; refs.detailContent.innerHTML = `<div class="detail-summary"><div><span>Identificador</span><strong>${escapeHtml(sample.id)}</strong></div><div><span>Estado</span><strong>${escapeHtml(sample.status)}</strong></div><div><span>Fuente</span><strong>${escapeHtml(sample.source)}</strong></div><div><span>Unidades</span><strong>${escapeHtml(sample.units)}</strong></div></div><p class="detail-description">${escapeHtml(sample.description)}</p><h3 class="detail-section-title">Estructura</h3><div class="detail-table-wrap"><table class="table table-sm align-middle mb-0"><thead><tr><th>Campo</th><th>Identificador</th><th>Precarga</th><th>Informante</th><th>Usuario</th></tr></thead><tbody>${fields.map((field) => `<tr><td>${escapeHtml(field.name)}</td><td>${field.unique ? "Sí" : "No"}</td><td>${field.preload ? "Sí" : "No"}</td><td>${field.informant ? "Sí" : "No"}</td><td>${field.user ? "Sí" : "No"}</td></tr>`).join("") || '<tr><td colspan="5">Sin campos configurados.</td></tr>'}</tbody></table></div><h3 class="detail-section-title">Selección e instrumentos</h3><p class="detail-trace">Método: <strong>${escapeHtml(sample.selectionMethod || "Aleatoria")}</strong> · Instrumentos: <strong>${escapeHtml(instruments.join(", ") || "Sin instrumentos")}</strong> · Unidades visibles: <strong>${units.length}</strong></p><p class="detail-trace">Última actualización: ${escapeHtml(sample.updated || "Sin registro")}</p>`; bootstrap.Modal.getOrCreateInstance(refs.detailModal).show(); }

export function validateStep(step = state.step) { clearErrors(); if (step === 1) { refs.nameError.textContent = refs.sampleName.value.trim() ? "" : "Ingresa el nombre de la muestra."; refs.descriptionError.textContent = refs.sampleDescription.value.trim() ? "" : "Ingresa la descripción de la muestra."; refs.sourceError.textContent = refs.sampleSource.value ? "" : "Selecciona una fuente activa."; const population = Number(state.draft?.population || 0), size = Number(refs.sampleSize.value); refs.sizeError.textContent = size > 0 && size <= population ? "" : population && size > population ? "El tamaño no puede superar la población." : "Ingresa un tamaño válido."; return Boolean(state.draft && refs.sampleName.value.trim() && refs.sampleDescription.value.trim() && refs.sampleSource.value && size > 0 && size <= population && refs.instrumentOptions.some((input) => input.checked)); } if (step === 2) return Boolean(state.draft?.fields?.length && state.draft.fields.some((field) => field.unique) && state.draft.fields.some((field) => field.informant) && state.draft.fields.some((field) => field.user)); if (step === 3) return Boolean(state.draft?.units?.length); return true; }
function persistDraft() { const previous = state.editingIndex === null ? null : samples[state.editingIndex]; if (!previous || !state.draft) return; Object.assign(previous, { ...state.draft, unitList: state.draft.units, units: previous.units || state.draft.sampleSize, updated: "21/08/2026 09:00" }); state.dirty = false; applyFilters(); }
export function requestSaveStep() { updateDraft(); if (!validateStep()) { showToast(getMessage("M12"), "warning"); return; } state.pendingAction = "saveStep"; openConfirmModal("confirmModal", getMessage("M1")); }
export function requestComplete() { updateDraft(); if (![1, 2, 3].every((step) => validateStep(step))) { showToast(getMessage("M12"), "warning"); return; } state.pendingAction = "complete"; openConfirmModal("confirmModal", getMessage("M1")); }
export function requestCancel() { if (!state.dirty) { resetWizard(); showList(); return; } state.pendingCancel = true; openConfirmModal("confirmModal", getMessage("M14")); }

export function confirmPendingAction() { if (state.pendingWizardStep) { const target = state.pendingWizardStep; state.pendingWizardStep = null; closeConfirmModal("confirmModal"); setFormStep(target); return; } if (state.pendingCancel) { closeConfirmModal("confirmModal"); resetWizard(); showList(); return; } if (state.pendingUnitAction?.type === "exclude") { state.draft.units = state.draft.units.filter((unit) => unit.id !== state.pendingUnitAction.unitId); state.dirty = true; state.pendingUnitAction = null; closeConfirmModal("confirmModal"); renderUnits(); showToast(getMessage("M3"), "success"); return; } if (state.pendingStatus) { const { index, next } = state.pendingStatus; if (next === "Inactiva" && !validateConfirmReason("confirmModal", getMessage("M11"))) return; samples[index].status = next; samples[index].updated = "21/08/2026 12:00"; if (next === "Inactiva") samples[index].inactivationReason = getConfirmReason("confirmModal"); state.pendingStatus = null; closeConfirmModal("confirmModal"); applyFilters(); showToast(getMessage(next === "Activa" ? "M7" : "M8"), "success"); return; } if (state.pendingAction === "saveStep") { persistDraft(); state.pendingAction = null; closeConfirmModal("confirmModal"); showToast(getMessage("M3"), "success"); return; } if (state.pendingAction === "complete") { const wasEditing = state.editingIndex !== null; const previous = wasEditing ? samples[state.editingIndex] : null; const payload = { id: previous?.id || `MST-${String(samples.length + 1).padStart(3, "0")}`, name: state.draft.name, description: state.draft.description, source: state.draft.source, sampleSize: state.draft.sampleSize, population: state.draft.population, unitTotal: state.draft.unitTotal, selectionMethod: state.draft.selectionMethod, fields: state.draft.fields, unitList: state.draft.units, units: previous?.units || state.draft.sampleSize, instruments: state.draft.instruments, status: "Activa", updated: "21/08/2026 09:00" }; if (wasEditing) samples[state.editingIndex] = payload; else samples.unshift(payload); state.pendingAction = null; closeConfirmModal("confirmModal"); resetWizard(); applyFilters(); showList(); showToast(getMessage(wasEditing ? "M3" : "M2"), "success"); } }

export function openReplacementModal(unitId) { const current = state.draft?.units?.find((unit) => unit.id === unitId); if (!current || !refs.replacementModal) return; state.replacementSelection = unitId; refs.replacementCurrent.innerHTML = `<div class="replacement-unit-icon"><i class="fa-regular fa-user" aria-hidden="true"></i></div><div class="replacement-current-info"><div><span>ID unidad</span><strong>${escapeHtml(current.id)}</strong></div><div><span>ID persona</span><strong>${escapeHtml(current.personId || "-")}</strong></div><div><span>Nombre completo</span><strong>${escapeHtml(current.name)}</strong></div><div><span>Región</span><strong>${escapeHtml(current.region || "-")}</strong></div><div><span>Distrito</span><strong>${escapeHtml(current.district || "-")}</strong></div><div><span>Fecha de nacimiento</span><strong>${escapeHtml(current.birthDate || "-")}</strong></div></div>`; refs.replacementSearch.value = ""; renderReplacementCandidates(); bootstrap.Modal.getOrCreateInstance(refs.replacementModal).show(); }
export function renderReplacementCandidates() { if (!refs.replacementBody || !state.draft) return; const query = (refs.replacementSearch?.value || "").trim().toLowerCase(); const currentIds = new Set(state.draft.units.map((unit) => unit.id)); const candidates = sampleUnitCatalog.filter((unit) => !currentIds.has(unit.id) && [unit.id, unit.personId, unit.name, unit.region, unit.district].join(" ").toLowerCase().includes(query)); refs.replacementBody.innerHTML = candidates.map((unit) => `<tr><td><input class="form-check-input" type="radio" name="replacementUnit" value="${escapeHtml(unit.id)}" ${state.replacementCandidate === unit.id ? "checked" : ""} aria-label="Seleccionar ${escapeHtml(unit.id)}"></td><td><strong>${escapeHtml(unit.id)}</strong></td><td>${escapeHtml(unit.personId)}</td><td>${escapeHtml(unit.name)}</td><td>${escapeHtml(unit.region)}</td><td>${escapeHtml(unit.district)}</td><td>${escapeHtml(unit.birthDate)}</td></tr>`).join("") || '<tr><td colspan="7" class="empty-inline">No hay unidades disponibles.</td></tr>'; }
export function confirmReplacement() { const selected = state.replacementCandidate || refs.replacementBody?.querySelector("input[name='replacementUnit']:checked")?.value; if (!selected || !state.draft || !state.replacementSelection) { showToast("Selecciona una unidad disponible.", "warning"); return; } const index = state.draft.units.findIndex((unit) => unit.id === state.replacementSelection); const replacement = sampleUnitCatalog.find((unit) => unit.id === selected); if (index < 0 || !replacement) return; state.draft.units[index] = { ...replacement }; state.dirty = true; state.replacementSelection = null; state.replacementCandidate = null; bootstrap.Modal.getOrCreateInstance(refs.replacementModal).hide(); renderUnits(); showToast(getMessage("M3"), "success"); }
export function exportRows(rows, filename, columns = [{ key: "id", label: "ID_UNIDAD" }, { key: "personId", label: "ID_PERSONA" }, { key: "name", label: "NOMBRE COMPLETO" }, { key: "region", label: "REGION" }, { key: "district", label: "DISTRITO" }, { key: "birthDate", label: "FECHA_NACIMIENTO" }]) { const headers = columns.map((column) => column.label); const csv = [headers, ...rows.map((row) => columns.map((column) => row[column.key] || ""))].map((line) => line.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(",")).join("\n"); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
export function updateField(index, key, value) { if (!state.draft?.fields[index]) return; state.draft.fields[index][key] = Boolean(value); state.dirty = true; }
export function addField() { if (!state.draft) return; state.draft.fields.push({ name: `Campo ${state.draft.fields.length + 1}`, unique: false, preload: false, informant: false, user: false }); state.dirty = true; }
