import { replacementUnitCatalog, samples, createSyntheticUnit } from "./data.js";
import { state, getSourceConfig, resetWizard } from "./state.js";
import { refs, enableTooltips, showToast, showForm, showList, setFormStep, clearErrors, updateDraft, renderAvailableFields, renderFields, renderUnits, getUnitColumns, getUnitDisplayValue } from "./ui.js";
import { openConfirmModal, closeConfirmModal, getConfirmReason, validateConfirmReason } from "../../design-system/interaction.js";
import { getMessage } from "../../design-system/messages.js";

const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]));
function statusClass(status) { return status === "Activo" ? "active" : status === "Inactivo" ? "inactive" : ""; }

export function renderSamples() { const header = refs.samplesBody.closest("table")?.querySelector("thead tr"); if (header && !header.querySelector("[data-column='row-number']")) header.insertAdjacentHTML("afterbegin", '<th data-column="row-number">N.°</th>'); refs.samplesBody.innerHTML = state.filteredSamples.map((sample) => { const index = samples.indexOf(sample); return `<tr><td>${index + 1}</td><td><strong>${escapeHtml(sample.name)}</strong><div class="description">${escapeHtml(sample.description)}</div></td><td>${escapeHtml(sample.source)}</td><td>${escapeHtml(sample.units)}</td><td><span class="status ${statusClass(sample.status)}">${escapeHtml(sample.status)}</span></td><td><div class="row-actions"><button class="row-action" type="button" data-action="view" data-index="${index}" title="Ver detalle"><i class="fa-regular fa-eye" aria-hidden="true"></i><span>Ver detalle</span></button><button class="row-action" type="button" data-action="edit" data-index="${index}" title="Editar"><i class="fa-solid fa-pen" aria-hidden="true"></i><span>Editar</span></button></div></td></tr>`; }).join(""); refs.emptyState.hidden = state.filteredSamples.length > 0; refs.pageSummary.textContent = state.filteredSamples.length ? `Mostrando 1 a ${state.filteredSamples.length} de ${state.filteredSamples.length} registros` : "Mostrando 0 registros"; refs.sampleCount.textContent = `${samples.length} muestras registradas`; enableTooltips(); }
export function applyFilters() { const query = refs.filterQuery.value.trim().toLowerCase(); const name = refs.filterName.value.trim().toLowerCase(); const records = refs.filterRecords.value.trim(); const source = refs.filterSource.value, status = refs.filterStatus.value; state.filteredSamples = samples.filter((sample) => { const searchable = [sample.name, sample.description, sample.source, sample.units, sample.status].join(" ").toLowerCase(); const sampleRecords = String(sample.units).replace(/[^0-9]/g, ""); return searchable.includes(query) && (!name || sample.name.toLowerCase().includes(name)) && (!records || sampleRecords.includes(records)) && (source === "Todos" || sample.source === source) && (status === "Todos" || sample.status === status); }); renderSamples(); }

export function prepareUnits() { if (!state.draft) return; const population = Number(state.draft.population || 0); const total = state.draft.selectionMethod === "Total" ? population : Number(state.draft.sampleSize || 0); const current = state.draft.units || []; const targetAmount = Math.max(0, total); state.draft.unitTotal = total; state.draft.units = Array.from({ length: targetAmount }, (_, index) => ({ ...createSyntheticUnit(index), ...(current[index] || {}), id: current[index]?.id || createSyntheticUnit(index).id })); }

export function handleAction(event) { const action = event.target.closest("[data-action]"); if (!action) return; if (["move-field-up", "move-field-down", "remove-field"].includes(action.dataset.action)) { const index = Number(action.dataset.fieldIndex); if (action.dataset.action === "remove-field") state.draft.fields.splice(index, 1); else { const next = action.dataset.action === "move-field-up" ? index - 1 : index + 1; if (state.draft.fields[next]) [state.draft.fields[index], state.draft.fields[next]] = [state.draft.fields[next], state.draft.fields[index]]; } state.dirty = true; renderAvailableFields(); renderFields(); return; } if (action.dataset.unitAction === "replace") { openReplacementModal(action.dataset.unitId); return; } const sample = samples[Number(action.dataset.index)]; if (!sample) return; if (action.dataset.action === "view") { showDetail(sample); return; } if (action.dataset.action === "edit") { state.editingIndex = samples.indexOf(sample); state.draft = { ...sample, fields: sample.fields?.map((field, index) => ({ informant: false, user: index === 0, ...field })), informantFields: [...(sample.informantFields || sample.fields?.filter((field) => field.informant).map((field) => field.name) || [])], units: sample.unitList?.map((unit) => ({ ...unit })), instruments: [...(sample.instruments || [])] }; showForm(sample); return; } }

function showDetail(sample) { const fields = sample.fields || [], informantFields = sample.informantFields || fields.filter((field) => field.informant).map((field) => field.name), units = sample.unitList || [], instruments = sample.instruments || []; refs.detailContent.innerHTML = `<div class="detail-summary"><div><span>Identificador</span><strong>${escapeHtml(sample.id)}</strong></div><div><span>Estado</span><strong>${escapeHtml(sample.status)}</strong></div><div><span>Proyecto</span><strong>${escapeHtml(sample.project || "No definido")}</strong></div><div><span>Fuente</span><strong>${escapeHtml(sample.source)}</strong></div><div><span>Unidades</span><strong>${escapeHtml(sample.units)}</strong></div></div><p class="detail-description">${escapeHtml(sample.description)}</p><h3 class="detail-section-title">Estructura</h3><div class="detail-table-wrap"><table class="table align-middle mb-0 ssee-table"><thead><tr><th>Orden</th><th>Campo</th><th>Precarga</th><th>Campo usuario</th></tr></thead><tbody>${fields.map((field, index) => `<tr><td>${index + 1}</td><td>${escapeHtml(field.name)}</td><td>${field.preload ? "Sí" : "No"}</td><td>${field.user ? "Sí" : "No"}</td></tr>`).join("") || '<tr><td colspan="4">Sin campos configurados.</td></tr>'}</tbody></table></div><div class="detail-trace-grid"><div><span>Informante</span><strong>${escapeHtml(informantFields.join(" + ") || "Sin configurar")}</strong></div></div><h3 class="detail-section-title">Selección e instrumentos</h3><div class="detail-trace-grid"><div><span>Método de selección</span><strong>${escapeHtml(sample.selectionMethod || "Aleatoria")}</strong></div><div><span>Instrumentos</span><strong>${escapeHtml(instruments.join(", ") || "Sin instrumentos")}</strong></div><div><span>Unidades visibles</span><strong>${units.length}</strong></div><div><span>Última actualización</span><strong>${escapeHtml(sample.updated || "Sin registro")}</strong></div></div>`; bootstrap.Modal.getOrCreateInstance(refs.detailModal).show(); }

export function validateStep(step = state.step) { clearErrors(); if (step === 1) { refs.nameError.textContent = refs.sampleName.value.trim() ? "" : "Ingresa el nombre de la muestra."; refs.descriptionError.textContent = refs.sampleDescription.value.trim() ? "" : "Ingresa la descripción de la muestra."; refs.projectError.textContent = refs.sampleProject.value ? "" : "Selecciona un proyecto."; refs.sourceError.textContent = refs.sampleSource.value ? "" : "Selecciona una fuente activa."; const instruments = [...refs.instrumentOptions.querySelectorAll("[data-instrument]")].filter((input) => input.checked); refs.instrumentError.textContent = instruments.length ? "" : "Selecciona al menos un instrumento del proyecto."; const population = Number(state.draft?.population || 0), size = Number(refs.sampleSize.value); refs.sizeError.textContent = size > 0 && size <= population ? "" : population && size > population ? "El tamaño no puede superar la población." : "Ingresa un tamaño válido."; return Boolean(state.draft && refs.sampleName.value.trim() && refs.sampleDescription.value.trim() && refs.sampleProject.value && refs.sampleSource.value && size > 0 && size <= population && instruments.length); } if (step === 2) { const informantFields = state.draft?.informantFields || []; const informantValid = state.draft?.informantMode === "concatenated" ? informantFields.length === 2 : informantFields.length === 1; return Boolean(state.draft?.fields?.length && state.draft.fields.some((field) => field.user) && informantValid); } if (step === 3) return Boolean(state.draft?.units?.length); return true; }
function persistDraft() { const previous = state.editingIndex === null ? null : samples[state.editingIndex]; if (!previous || !state.draft) return; Object.assign(previous, { ...state.draft, unitList: state.draft.units, informantFields: state.draft.informantFields, units: previous.units || state.draft.sampleSize, updated: "21/08/2026 09:00" }); state.dirty = false; applyFilters(); }
export function requestSaveStep() { updateDraft(); if (!validateStep()) { showToast(getMessage("M12"), "warning"); return; } state.pendingAction = "saveStep"; openConfirmModal("confirmModal", getMessage("M1")); }
export function requestComplete() { updateDraft(); if (![1, 2, 3].every((step) => validateStep(step))) { showToast(getMessage("M12"), "warning"); return; } state.pendingAction = "complete"; openConfirmModal("confirmModal", getMessage("M1")); }
export function requestCancel() { if (!state.dirty) { resetWizard(); showList(); return; } state.pendingCancel = true; openConfirmModal("confirmModal", getMessage("M14")); }

export function confirmPendingAction() { if (state.pendingWizardStep) { const target = state.pendingWizardStep; state.pendingWizardStep = null; closeConfirmModal("confirmModal"); setFormStep(target); return; } if (state.pendingCancel) { closeConfirmModal("confirmModal"); resetWizard(); showList(); return; } if (state.pendingStatus) { const { index, next } = state.pendingStatus; if (next === "Inactivo" && !validateConfirmReason("confirmModal", getMessage("M11"))) return; samples[index].status = next; samples[index].updated = "21/08/2026 12:00"; if (next === "Inactivo") samples[index].inactivationReason = getConfirmReason("confirmModal"); state.pendingStatus = null; closeConfirmModal("confirmModal"); applyFilters(); showToast(getMessage(next === "Activo" ? "M7" : "M8"), "success"); return; } if (state.pendingAction === "saveStep") { persistDraft(); state.pendingAction = null; closeConfirmModal("confirmModal"); showToast(getMessage("M3"), "success"); return; } if (state.pendingAction === "complete") { const wasEditing = state.editingIndex !== null; const previous = wasEditing ? samples[state.editingIndex] : null; const payload = { id: previous?.id || `MST-${String(samples.length + 1).padStart(3, "0")}`, name: state.draft.name, description: state.draft.description, project: state.draft.project, source: state.draft.source, sampleSize: state.draft.sampleSize, population: state.draft.population, unitTotal: state.draft.unitTotal, selectionMethod: state.draft.selectionMethod, fields: state.draft.fields, unitList: state.draft.units, informantFields: state.draft.informantFields, units: previous?.units || state.draft.sampleSize, instruments: state.draft.instruments, status: "Activo", updated: "21/08/2026 09:00" }; if (wasEditing) samples[state.editingIndex] = payload; else samples.unshift(payload); state.pendingAction = null; closeConfirmModal("confirmModal"); resetWizard(); applyFilters(); showList(); showToast(getMessage(wasEditing ? "M3" : "M2"), "success"); } }

export function openReplacementModal(unitId) { const current = state.draft?.units?.find((unit) => unit.id === unitId); if (!current || !refs.replacementModal) return; state.replacementSelection = unitId; const columns = getUnitColumns(); const currentIndex = state.draft.units.indexOf(current); refs.replacementCurrent.innerHTML = `<div class="replacement-unit-icon"><i class="fa-regular fa-user" aria-hidden="true"></i></div><div class="replacement-current-info">${columns.map((column) => `<div><span>${escapeHtml(column.label)}</span><strong>${escapeHtml(getUnitDisplayValue(current, column, currentIndex))}</strong></div>`).join("")}</div>`; if (refs.replacementConfig) { const selectedFields = (state.draft.fields || []).map((field) => field.name); const informant = (state.draft.informantFields || []).join(" + ") || "Sin configurar"; refs.replacementConfig.innerHTML = `<span>Configuración de la muestra</span><strong>Campos seleccionados: ${escapeHtml(selectedFields.join(", ") || "Sin campos")} · Informante: ${escapeHtml(informant)}</strong>`; } refs.replacementSearch.value = ""; renderReplacementCandidates(); bootstrap.Modal.getOrCreateInstance(refs.replacementModal).show(); }
export function renderReplacementCandidates() { if (!refs.replacementBody || !state.draft) return; const columns = getUnitColumns(); const header = refs.replacementBody.closest("table")?.querySelector("thead tr"); if (header) header.innerHTML = `<th>Seleccionar</th>${columns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join("")}`; const query = (refs.replacementSearch?.value || "").trim().toLowerCase(); const currentIds = new Set(state.draft.units.map((unit) => unit.id)); const candidates = replacementUnitCatalog.filter((unit) => !currentIds.has(unit.id) && columns.map((column) => getUnitDisplayValue(unit, column, replacementUnitCatalog.indexOf(unit))).join(" ").toLowerCase().includes(query)); refs.replacementBody.innerHTML = candidates.map((unit) => { const index = replacementUnitCatalog.indexOf(unit); return `<tr><td><input class="form-check-input" type="radio" name="replacementUnit" value="${escapeHtml(unit.id)}" ${state.replacementCandidate === unit.id ? "checked" : ""} aria-label="Seleccionar ${escapeHtml(unit.id)}"></td>${columns.map((column) => `<td>${column.key === "field:NOMBRE_COMPLETO" ? `<strong>${escapeHtml(getUnitDisplayValue(unit, column, index))}</strong>` : escapeHtml(getUnitDisplayValue(unit, column, index))}</td>`).join("")}</tr>`; }).join("") || `<tr><td colspan="${columns.length + 1}" class="empty-inline">No hay unidades disponibles.</td></tr>`; }
export function confirmReplacement() { const selected = state.replacementCandidate || refs.replacementBody?.querySelector("input[name='replacementUnit']:checked")?.value; if (!selected || !state.draft || !state.replacementSelection) { showToast("Selecciona una unidad disponible.", "warning"); return; } const index = state.draft.units.findIndex((unit) => unit.id === state.replacementSelection); const replacement = replacementUnitCatalog.find((unit) => unit.id === selected); if (index < 0 || !replacement) return; state.draft.units[index] = { ...replacement }; state.dirty = true; state.replacementSelection = null; state.replacementCandidate = null; bootstrap.Modal.getOrCreateInstance(refs.replacementModal).hide(); renderUnits(); showToast(getMessage("M3"), "success"); }
export function exportRows(rows, filename, columns = [{ key: "id", label: "ID_UNIDAD" }, { key: "personId", label: "ID_PERSONA" }, { key: "name", label: "NOMBRE COMPLETO" }, { key: "region", label: "REGION" }, { key: "district", label: "DISTRITO" }, { key: "birthDate", label: "FECHA_NACIMIENTO" }]) { const headers = columns.map((column) => column.label); const csv = [headers, ...rows.map((row) => columns.map((column) => row[column.key] || ""))].map((line) => line.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(",")).join("\n"); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
export function updateField(index, key, value) { if (!state.draft?.fields[index]) return; if (key === "user" && value) state.draft.fields.forEach((field, fieldIndex) => { field.user = fieldIndex === index; }); else state.draft.fields[index][key] = Boolean(value); state.dirty = true; }
export function addField() { if (!state.draft) return; state.draft.fields.push({ name: `Campo ${state.draft.fields.length + 1}`, unique: false, preload: false, informant: false, user: false }); state.dirty = true; }
